function Hd = gw_signal
%GW_SIGNAL Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 14-Jul-2015 14:23:07

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass1 = 7200;           % First Passband Frequency
Fstop1 = 9600;           % First Stopband Frequency
Fstop2 = 12000;          % Second Stopband Frequency
Fpass2 = 14400;          % Second Passband Frequency
Dpass1 = 0.99369538163;  % First Passband Ripple
Dstop  = 0.1;            % Stopband Attenuation
Dpass2 = 0.99369538163;  % Second Passband Ripple
dens   = 20;             % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
